### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by shawnLOATRchen** [aleksei0807/react-images-uploader#1]
when I trying to import cors-prefetch-middleware, it shows error
es6 is working fine in my code, but I don't know why I cannot import this

(function (exports, require, module, __filename, __dirname) { import corsPrefetch from 'cors-prefetch-middleware';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\project\mainCtrl.js:7:15)
    at Module._compile (module.js:570:32)

**Comment by aleksei0807** [comment]
you should transpile examples with babel to use them.

**Comment by masummillat** [comment]
could you please explain how to transpile with bable
